name: Clippy and Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --no-default-features --features tracing

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
    
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
  
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --no-default-features --no-fail-fast --failure-output=immediate-final

      - name: Run doctests
        run: cargo test --doc

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check README
        run: |
          cargo install cargo-rdme
          cargo rdme --check